// Generated by unRap v1.06 by Kegetys

class cfgWeapons {
    class InventoryItem_Base_F;
    class ItemCore;
    class ItemInfo;
    class H_HelmetIA;
    class UniformItem: InventoryItem_Base_F {
        type = 801;
    };
    class Uniform_Base: ItemCore {
        scope = public;
        allowedSlots[] = {
            901
        };
        class ItemInfo: UniformItem {
            uniformModel = "-";
            uniformClass = "B_Soldier_F";
            containerClass = "Supply0";
            mass = 0;
        };
    };
    class U_B_CombatUniform_mcam;
    class U_B_CombatUniform_mcam_tshirt;
    class U_B_CombatUniform_mcam_vest;
    class VestItem;
    class Vest_Base;
    class V_Rangemaster_belt;
    class V_BandollierB_khk;
    class V_BandollierB_rgr;
    class V_BandollierB_cbr;
    class V_PlateCarrier1_rgr;
    class V_PlateCarrier1_cbr;
    class V_PlateCarrier2_rgr;
    class H_HelmetB;
    class H_HelmetB_paint;
    class H_HelmetB_light;
    class H_HelmetSpecB;
    class H_MilCap_mcamo;
    class H_Cap_headphones;
    class U_BasicBody;
    class V_PlateCarrierIA1_dgtl;
    class V_PlateCarrierIA2_dgtl;
    class H_Bandanna_surfer;
    class H_PilotHelmetHeli_B;
    class H_HelmetB_camo;


// ARMA HELMET




    class ARC_Common_MEF_Helmet : H_HelmetSpecB {
        displayName = "(ARC) Common Equipped MICH 2000 (MiddleEastForest)";
        picture = "\Common_items\data\Helmet\Icon_common_equip.paa";
        hiddenSelections[] = {"camo"};
        hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\Common_MEF_equip.paa"};
        
        class ItemInfo: ItemInfo {
          mass = 50;
          modelsides[] = {3, 1};
          uniformmodel = "\A3\Characters_F\BLUFOR\headgear_b_helmet_ballistic";

          class HitpointsProtectionInfo {
            class Head {
                hitpointName = "HitHead";
                armor = 5;
                passThrough = 0.500000;
            };
        };
    };
};

class ARC_Common_MEF_Helmet_G : H_HelmetB_camo {
    displayName = "(ARC) Common Camo MICH 2000 (MiddleEastForest)";	
    model = "\A3\Characters_F\BLUFOR\headgear_b_helmet_camo";
    hiddenSelections[] = {"camo1", "camo2"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\Common_MEF_equip.paa", "\A3\characters_f\common\data\ghillie2_co.paa"};

    class ItemInfo : ItemInfo {
     uniformModel = "\A3\Characters_F\BLUFOR\headgear_b_helmet_camo";
     hiddenSelections[] = {"camo1", "camo2"};
     mass = 50;

     class HitpointsProtectionInfo {
        class Head {
            hitpointName = "HitHead";
            armor = 5;
            passThrough = 0.500000;
        };
    };		
};
};	
class ARC_Common_Snow_Helmet_G : H_HelmetB_camo {
    displayName = "(ARC) Common Camo MICH 2000 (Snow)";	
    model = "\A3\Characters_F\BLUFOR\headgear_b_helmet_camo";
    hiddenSelections[] = {"camo1", "camo2"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\Common_Snow_equip.paa", "\A3\characters_f\common\data\ghillie2_co.paa"};

    class ItemInfo : ItemInfo {
     uniformModel = "\A3\Characters_F\BLUFOR\headgear_b_helmet_camo";
     hiddenSelections[] = {"camo1", "camo2"};
     mass = 50;

     class HitpointsProtectionInfo {
        class Head {
            hitpointName = "HitHead";
            armor = 5;
            passThrough = 0.500000;
        };
    };		
};
};		
class ARC_Common_MEF_Helmet_simple : H_HelmetB {
    displayName = "(ARC) Common MICH 2000 (MiddleEastForest)";
    picture = "\Common_items\data\Helmet\Icon_common_equip.paa";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\Common_MEF_equip.paa"};

    class ItemInfo: ItemInfo {
        allowedslots[] = {801, 901, 701, 605};
        mass = 10;
        modelsides[] = {6};
        uniformmodel = "\A3\Characters_F\BLUFOR\headgear_b_helmet_plain";

        class HitpointsProtectionInfo {
            class Head {
                hitpointName = "HitHead";
                armor = 5;
                passThrough = 1;
            };
        };
    };
};

class ARC_Common_MEF_Helmet_Light : H_HelmetB_light {
    displayName = "(ARC) Common FBJ Ops Core (MiddleEastForest)";
    picture = "\Common_items\data\Helmet\Icon_common_equip.paa";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\Common_MEF_equip.paa"};

    class ItemInfo: ItemInfo {
      mass = 30;
      uniformmodel = "\A3\Characters_F\BLUFOR\headgear_b_helmet_light";

      class HitpointsProtectionInfo {
        class Head {
            hitpointName = "HitHead";
            armor = 3;
            passThrough = 0.500000;
        };
    };
};
};

//
class ARC_Common_FG_Helmet : H_HelmetSpecB {
    displayName = "(ARC) Common Equipped MICH 2000 (FG)";
    picture = "\Common_items\data\Helmet\Icon_common_equip.paa";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\Common_FG_equip.paa"};

    class ItemInfo: ItemInfo {
      mass = 50;
      modelsides[] = {3, 1};
      uniformmodel = "\A3\Characters_F\BLUFOR\headgear_b_helmet_ballistic";

      class HitpointsProtectionInfo {
        class Head {
            hitpointName = "HitHead";
            armor = 5;
            passThrough = 0.500000;
        };
    };
};
};

class ARC_Common_FG_Helmet_simple : H_HelmetB {
    displayName = "(ARC) Common MICH 2000 (FG)";
    picture = "\Common_items\data\Helmet\Icon_common_equip.paa";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\Common_FG_equip.paa"};

    class ItemInfo: ItemInfo {
        allowedslots[] = {801, 901, 701, 605};
        mass = 10;
        modelsides[] = {6};
        uniformmodel = "\A3\Characters_F\BLUFOR\headgear_b_helmet_plain";

        class HitpointsProtectionInfo {
            class Head {
                hitpointName = "HitHead";
                armor = 5;
                passThrough = 1.000000;
            };
        };
    };
};

class ARC_Common_FG_Helmet_Light : H_HelmetB_light {
    displayName = "(ARC) Common FBJ Ops Core (FG)";
    picture = "\Common_items\data\Helmet\Icon_common_equip.paa";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\Common_FG_equip.paa"};

    class ItemInfo: ItemInfo {
      mass = 30;
      uniformmodel = "\A3\Characters_F\BLUFOR\headgear_b_helmet_light";

      class HitpointsProtectionInfo {
        class Head {
            hitpointName = "HitHead";
            armor = 3;
            passThrough = 0.500000;
        };
    };
};
};
//
class ARC_Common_Desert_Helmet : H_HelmetSpecB {
    displayName = "(ARC) Common Equipped MICH 2000 (Desert)";
    picture = "\Common_items\data\Helmet\Icon_common_equip.paa";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\Common_Desert_equip.paa"};

    class ItemInfo: ItemInfo {
      mass = 50;
      modelsides[] = {3, 1};
      uniformmodel = "\A3\Characters_F\BLUFOR\headgear_b_helmet_ballistic";

      class HitpointsProtectionInfo {
        class Head {
            hitpointName = "HitHead";
            armor = 5;
            passThrough = 0.500000;
        };
    };

};
};

class ARC_Common_Desert_Helmet_simple : H_HelmetB {
    displayName = "(ARC) Common MICH 2000 (Desert)";
    picture = "\Common_items\data\Helmet\Icon_common_equip.paa";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\Common_Desert_equip.paa"};

    class ItemInfo: ItemInfo {
        allowedslots[] = {801, 901, 701, 605};
        mass = 10;
        modelsides[] = {6};
        uniformmodel = "\A3\Characters_F\BLUFOR\headgear_b_helmet_plain";

        class HitpointsProtectionInfo {
            class Head {
                hitpointName = "HitHead";
                armor = 5;
                passThrough = 1.000000;
            };
        };
    };
};

class ARC_Common_Desert_Helmet_Light : H_HelmetB_light {
    displayName = "(ARC) Common FBJ Ops Core (Desert)";
    picture = "\Common_items\data\Helmet\Icon_common_equip.paa";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\Common_Desert_equip.paa"};

    class ItemInfo: ItemInfo {
      mass = 30;
      uniformmodel = "\A3\Characters_F\BLUFOR\headgear_b_helmet_light";

      class HitpointsProtectionInfo {
        class Head {
            hitpointName = "HitHead";
            armor = 3;
            passThrough = 0.500000;
        };
    };
};
};
//
class ARC_Common_Black_Helmet : H_HelmetSpecB {
    displayName = "(ARC) Common Equipped MICH 2000 (Black)";
    picture = "\Common_items\data\Helmet\Icon_common_equip.paa";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\Common_Black_equip.paa"};

    class ItemInfo: ItemInfo {
      mass = 50;
      modelsides[] = {3, 1};
      uniformmodel = "\A3\Characters_F\BLUFOR\headgear_b_helmet_ballistic";

      class HitpointsProtectionInfo {
        class Head {
            hitpointName = "HitHead";
            armor = 5;
            passThrough = 0.500000;
        };
    };
};
};

class ARC_Common_Black_M_Helmet : H_HelmetSpecB {
    displayName = "(ARC) Common MICH 2000 Medic (Black)";
    picture = "\Common_items\data\Helmet\Icon_common_equip.paa";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\Common_Black_M_equip.paa"};

    class ItemInfo: ItemInfo {
        mass = 50;
        modelsides[] = {3, 1};
        uniformmodel = "\A3\Characters_F\BLUFOR\headgear_b_helmet_plain";

        class HitpointsProtectionInfo {
            class Head {
                hitpointName = "HitHead";
                armor = 5;
                passThrough = 0.500000;
            };
        };        
    };
};	

class ARC_Common_Black_Helmet_simple : H_HelmetB {
    displayName = "(ARC) Common MICH 2000 (Black)";
    picture = "\Common_items\data\Helmet\Icon_common_equip.paa";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\Common_Black_equip.paa"};

    class ItemInfo: ItemInfo {
        allowedslots[] = {801, 901, 701, 605};
        mass = 10;
        modelsides[] = {6};
        uniformmodel = "\A3\Characters_F\BLUFOR\headgear_b_helmet_plain";

        class HitpointsProtectionInfo {
            class Head {
                hitpointName = "HitHead";
                armor = 5;
                passThrough = 1.000000;
            };
        };
    };
};

class ARC_Common_Black_Helmet_Light : H_HelmetB_light {
    displayName = "(ARC) Common FBJ Ops Core (Black)";
    picture = "\Common_items\data\Helmet\Icon_common_equip.paa";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\Common_Black_equip.paa"};

    class ItemInfo: ItemInfo {
        armor = 3;
        mass = 30;
        passthrough = 0.5;
        uniformmodel = "\A3\Characters_F\BLUFOR\headgear_b_helmet_light";

        class HitpointsProtectionInfo {
            class Head {
                hitpointName = "HitHead";
                armor = 3;
                passThrough = 0.500000;
            };
        };
    };
};

class ARC_Common_Black_M_Helmet_Light : H_HelmetB_light {
    displayName = "(ARC) Common FBJ Ops Core Medic (Black)";
    picture = "\Common_items\data\Helmet\Icon_common_equip.paa";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\Common_Black_M_equip.paa"};

    class ItemInfo: ItemInfo {
        mass = 30;
        uniformmodel = "\A3\Characters_F\BLUFOR\headgear_b_helmet_light";

        class HitpointsProtectionInfo {
            class Head {
                hitpointName = "HitHead";
                armor = 3;
                passThrough = 0.500000;
            };
        };
    };
};	
//
class ARC_Common_OD_Helmet : H_HelmetSpecB {
    displayName = "(ARC) Common Equipped MICH 2000 (OD)";
    picture = "\Common_items\data\Helmet\Icon_common_equip.paa";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\Common_OD_equip.paa"};

    class ItemInfo: ItemInfo {
        mass = 50;
        modelsides[] = {3, 1};
        uniformmodel = "\A3\Characters_F\BLUFOR\headgear_b_helmet_ballistic";

         class HitpointsProtectionInfo {
            class Head {
                hitpointName = "HitHead";
                armor = 5;
                passThrough = 0.500000;
            };
        };
    };
};

class ARC_Common_OD_M_Helmet : H_HelmetSpecB {
    displayName = "(ARC) Common MICH 2000 Medic (OD)";
    picture = "\Common_items\data\Helmet\Icon_common_equip.paa";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\Common_OD_M_equip.paa"};

    class ItemInfo: ItemInfo {
        mass = 50;
        modelsides[] = {3, 1};
        uniformmodel = "\A3\Characters_F\BLUFOR\headgear_b_helmet_plain";

        class HitpointsProtectionInfo {
            class Head {
                hitpointName = "HitHead";
                armor = 5;
                passThrough = 0.500000;
            };
        };
    };
};	

class ARC_Common_OD_Helmet_simple : H_HelmetB {
    displayName = "(ARC) Common MICH 2000 (OD)";
    picture = "\Common_items\data\Helmet\Icon_common_equip.paa";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\Common_OD_equip.paa"};

    class ItemInfo: ItemInfo {
        allowedslots[] = {801, 901, 701, 605};
        mass = 10;
        modelsides[] = {6};
        uniformmodel = "\A3\Characters_F\BLUFOR\headgear_b_helmet_plain";

        class HitpointsProtectionInfo {
            class Head {
                hitpointName = "HitHead";
                armor = 5;
                passThrough = 1.000000;
            };
        };
    };
};

class ARC_Common_OD_Helmet_Light : H_HelmetB_light {
    displayName = "(ARC) Common FBJ Ops Core (OD)";
    picture = "\Common_items\data\Helmet\Icon_common_equip.paa";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\Common_OD_equip.paa"};

    class ItemInfo: ItemInfo {
        mass = 30;
        uniformmodel = "\A3\Characters_F\BLUFOR\headgear_b_helmet_light";

        class HitpointsProtectionInfo {
            class Head {
                hitpointName = "HitHead";
                armor = 3;
                passThrough = 0.500000;
            };
        };
    };
};

class ARC_Common_OD_M_Helmet_Light : H_HelmetB_light {
    displayName = "(ARC) Common FBJ Ops Core Medic (OD)";
    picture = "\Common_items\data\Helmet\Icon_common_equip.paa";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\Common_OD_M_equip.paa"};

    class ItemInfo: ItemInfo {
        mass = 30;
        uniformmodel = "\A3\Characters_F\BLUFOR\headgear_b_helmet_light";

        class HitpointsProtectionInfo {
            class Head {
                hitpointName = "HitHead";
                armor = 3;
                passThrough = 0.500000;
            };
        };
    };
};	
//
class ARC_Common_TAN_Helmet : H_HelmetSpecB {
    displayName = "(ARC) Common Equipped MICH 2000 (TAN)";
    picture = "\Common_items\data\Helmet\Icon_common_equip.paa";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\Common_TAN_equip.paa"};

    class ItemInfo: ItemInfo {
        mass = 50;
        modelsides[] = {3, 1};
        uniformmodel = "\A3\Characters_F\BLUFOR\headgear_b_helmet_ballistic";

        class HitpointsProtectionInfo {
            class Head {
                hitpointName = "HitHead";
                armor = 5;
                passThrough = 0.500000;
            };
        };
    };
};

class ARC_Common_TAN_M_Helmet : H_HelmetSpecB {
    displayName = "(ARC) Common MICH 2000 Medic (TAN)";
    picture = "\Common_items\data\Helmet\Icon_common_equip.paa";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\Common_TAN_M_equip.paa"};

    class ItemInfo: ItemInfo {
        mass = 50;
        modelsides[] = {3, 1};
        uniformmodel = "\A3\Characters_F\BLUFOR\headgear_b_helmet_plain";

        class HitpointsProtectionInfo {
            class Head {
                hitpointName = "HitHead";
                armor = 5;
                passThrough = 0.500000;
            };
        };
    };
};	

class ARC_Common_TAN_Helmet_simple : H_HelmetB {
    displayName = "(ARC) Common MICH 2000 (TAN)";
    picture = "\Common_items\data\Helmet\Icon_common_equip.paa";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\Common_TAN_equip.paa"};

    class ItemInfo: ItemInfo {
        allowedslots[] = {801, 901, 701, 605};
        mass = 10;
        modelsides[] = {6};
        uniformmodel = "\A3\Characters_F\BLUFOR\headgear_b_helmet_plain";

        class HitpointsProtectionInfo {
            class Head {
                hitpointName = "HitHead";
                armor = 5;
                passThrough = 1.000000;
            };
        };
    };
};

class ARC_Common_TAN_Helmet_Light : H_HelmetB_light {
    displayName = "(ARC) Common FBJ Ops Core (TAN)";
    picture = "\Common_items\data\Helmet\Icon_common_equip.paa";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\Common_TAN_equip.paa"};

    class ItemInfo: ItemInfo {
        mass = 30;
        uniformmodel = "\A3\Characters_F\BLUFOR\headgear_b_helmet_light";

        class HitpointsProtectionInfo {
            class Head {
                hitpointName = "HitHead";
                armor = 3;
                passThrough = 0.500000;
            };
        };
    };
};

class ARC_Common_TAN_M_Helmet_Light : H_HelmetB_light {
    displayName = "(ARC) Common FBJ Ops Core Medic (TAN)";
    picture = "\Common_items\data\Helmet\Icon_common_equip.paa";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\Common_TAN_M_equip.paa"};

    class ItemInfo: ItemInfo {
        mass = 30;
        uniformmodel = "\A3\Characters_F\BLUFOR\headgear_b_helmet_light";

        class HitpointsProtectionInfo {
            class Head {
                hitpointName = "HitHead";
                armor = 3;
                passThrough = 0.500000;
            };
        };
    };
};	
//

class ARC_Common_AllAllBlack_Helmet : H_HelmetSpecB {
    displayName = "(ARC) Common Equipped MICH 2000 (AllBlack)";
    picture = "\Common_items\data\Helmet\Icon_common_equip.paa";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\Common_AllBlack_equip.paa"};

    class ItemInfo: ItemInfo {
        mass = 50;
        modelsides[] = {3, 1};
        uniformmodel = "\A3\Characters_F\BLUFOR\headgear_b_helmet_ballistic";

        class HitpointsProtectionInfo {
            class Head {
                hitpointName = "HitHead";
                armor = 5;
                passThrough = 0.500000;
            };
        };
    };
};	

class ARC_Common_AllBlack_Helmet_simple : H_HelmetB {
    displayName = "(ARC) Common MICH 2000 (AllBlack)";
    picture = "\Common_items\data\Helmet\Icon_common_equip.paa";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\Common_AllBlack_equip.paa"};

    class ItemInfo: ItemInfo {
        allowedslots[] = {801, 901, 701, 605};
        mass = 10;
        modelsides[] = {6};
        uniformmodel = "\A3\Characters_F\BLUFOR\headgear_b_helmet_plain";

         class HitpointsProtectionInfo {
            class Head {
                hitpointName = "HitHead";
                armor = 5;
                passThrough = 1.000000;
            };
        };
    };
};

class ARC_Common_AllBlack_Helmet_Light : H_HelmetB_light {
    displayName = "(ARC) Common FBJ Ops Core (AllBlack)";
    picture = "\Common_items\data\Helmet\Icon_common_equip.paa";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\Common_AllBlack_equip.paa"};

    class ItemInfo: ItemInfo {
        mass = 30;
        uniformmodel = "\A3\Characters_F\BLUFOR\headgear_b_helmet_light";

        class HitpointsProtectionInfo {
            class Head {
                hitpointName = "HitHead";
                armor = 3;
                passThrough = 0.500000;
            };
        };
    };
};
//
class ARC_Common_ATACS_LE_Helmet : H_HelmetSpecB {
    displayName = "(ARC) Common Equipped MICH 2000 (ATACS LE)";
    picture = "\Common_items\data\Helmet\Icon_common_equip.paa";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\Common_ATACS_LE_equip.paa"};

    class ItemInfo: ItemInfo {
        mass = 50;
        modelsides[] = {3, 1};
        uniformmodel = "\A3\Characters_F\BLUFOR\headgear_b_helmet_ballistic";

        class HitpointsProtectionInfo {
            class Head {
                hitpointName = "HitHead";
                armor = 5;
                passThrough = 0.500000;
            };
        };
    };
};

class ARC_Common_ATACS_LE_M_Helmet : H_HelmetSpecB {
    displayName = "(ARC) Common MICH 2000 Medic (ATACS LE)";
    picture = "\Common_items\data\Helmet\Icon_common_equip.paa";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\Common_ATACS_LE_M_equip.paa"};

    class ItemInfo: ItemInfo {
        mass = 50;
        modelsides[] = {3, 1};
        uniformmodel = "\A3\Characters_F\BLUFOR\headgear_b_helmet_plain";

        class HitpointsProtectionInfo {
            class Head {
                hitpointName = "HitHead";
                armor = 5;
                passThrough = 0.500000;
            };
        };
    };
};	

class ARC_Common_ATACS_LE_Helmet_simple : H_HelmetB {
    displayName = "(ARC) Common MICH 2000 (ATACS LE)";
    picture = "\Common_items\data\Helmet\Icon_common_equip.paa";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\Common_ATACS_LE_equip.paa"};

    class ItemInfo: ItemInfo {
        allowedslots[] = {801, 901, 701, 605};
        mass = 10;
        modelsides[] = {6};
        uniformmodel = "\A3\Characters_F\BLUFOR\headgear_b_helmet_plain";

        class HitpointsProtectionInfo {
            class Head {
                hitpointName = "HitHead";
                armor = 5;
                passThrough = 1.000000;
            };
        };
    };
};

class ARC_Common_ATACS_LE_Helmet_Light : H_HelmetB_light {
    displayName = "(ARC) Common FBJ Ops Core (ATACS LE)";
    picture = "\Common_items\data\Helmet\Icon_common_equip.paa";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\Common_ATACS_LE_equip.paa"};

    class ItemInfo: ItemInfo {
        mass = 30;
        uniformmodel = "\A3\Characters_F\BLUFOR\headgear_b_helmet_light";

        class HitpointsProtectionInfo {
            class Head {
                hitpointName = "HitHead";
                armor = 3;
                passThrough = 0.500000;
            };
        };
    };
};

class ARC_Common_ATACS_LE_M_Helmet_Light : H_HelmetB_light {
    displayName = "(ARC) Common FBJ Ops Core Medic (ATACS LE)";
    picture = "\Common_items\data\Helmet\Icon_common_equip.paa";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\Common_ATACS_LE_M_equip.paa"};

    class ItemInfo: ItemInfo {
        mass = 30;
        uniformmodel = "\A3\Characters_F\BLUFOR\headgear_b_helmet_light";

        class HitpointsProtectionInfo {
            class Head {
                hitpointName = "HitHead";
                armor = 3;
                passThrough = 0.500000;
            };
        };
    };
};	
//	
class ARC_UN_M2000 : H_HelmetIA {
    displayName = "(ARC) Common UN PASGT";
    picture = "\Common_items\data\UI\icon_Common_UN_MICH.paa";
    model = "\A3\Characters_F_Beta\INDEP\headgear_helmet_canvas";
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\MICH2000_UN.paa"};
    class ItemInfo: ItemInfo {
        allowedslots[] = {901, 605};
        mass = 40;
        modelsides[] = {2, 3};
        uniformmodel = "\A3\Characters_F_Beta\INDEP\headgear_helmet_canvas.p3d";

        class HitpointsProtectionInfo {
            class Head {
                hitpointName = "HitHead";
                armor = 4;
                passThrough = 0.500000;
            };
        };
    };	
};


class ARC_Black_M2000 : H_HelmetIA {
    displayName = "(ARC) Common PASGT (Cover-Black)";
    picture = "\Common_items\data\UI\icon_Common_Black_MICH.paa";
    model = "\A3\Characters_F_Beta\INDEP\headgear_helmet_canvas";
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\MICH2000_Black.paa"};
    class ItemInfo: ItemInfo {
        allowedslots[] = {901, 605};
        mass = 40;
        modelsides[] = {2, 3};
        uniformmodel = "\A3\Characters_F_Beta\INDEP\headgear_helmet_canvas.p3d";

        class HitpointsProtectionInfo {
            class Head {
                hitpointName = "HitHead";
                armor = 4;
                passThrough = 0.500000;
            };
        };
    };	
};	

class ARC_OD_M2000 : H_HelmetIA {
    displayName = "(ARC) Common PASGT (Cover-OD)";
    picture = "\Common_items\data\UI\icon_Common_OD_MICH.paa";
    model = "\A3\Characters_F_Beta\INDEP\headgear_helmet_canvas";
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\MICH2000_OD.paa"};
    class ItemInfo: ItemInfo {
        allowedslots[] = {901, 605};
        mass = 40;
        modelsides[] = {2, 3};
        uniformmodel = "\A3\Characters_F_Beta\INDEP\headgear_helmet_canvas.p3d";

        class HitpointsProtectionInfo {
            class Head {
                hitpointName = "HitHead";
                armor = 4;
                passThrough = 0.500000;
            };
        };
    };		
};	

class ARC_TAN_M2000 : H_HelmetIA {
    displayName = "(ARC) Common PASGT (Cover-TAN)";
    picture = "\Common_items\data\UI\icon_Common_OD_MICH.paa";
    model = "\A3\Characters_F_Beta\INDEP\headgear_helmet_canvas";
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\MICH2000_TAN.paa"};
    class ItemInfo: ItemInfo {
        allowedslots[] = {901, 605};
        mass = 40;
        modelsides[] = {2, 3};
        uniformmodel = "\A3\Characters_F_Beta\INDEP\headgear_helmet_canvas.p3d";

        class HitpointsProtectionInfo {
            class Head {
                hitpointName = "HitHead";
                armor = 4;
                passThrough = 0.500000;
            };
        };
    };		
};	


//// Vests
// OD
class ARC_Common_OD_Plate_Carrier : V_PlateCarrier1_rgr {
  picture = "\Common_items\data\UI\Icon_Common_OD_vests.paa";	
  displayName = "(ARC) Common Plate Carrier (OD)";
  hiddenSelections[] = {"camo"};
  hiddenSelectionsTextures[] = {"\Common_items\data\Vests\Common_OD_vests.paa"};

      class ItemInfo: VestItem {
        containerclass = "Supply140";
        mass = 60;
        uniformmodel = "\A3\Characters_F\BLUFOR\equip_b_vest02";
        hiddenSelections[] = {
            "camo"
        };

        class HitpointsProtectionInfo {

            class Chest {
                HitpointName = "HitChest";
                armor = 20;
                PassThrough = 0.500000;
            };

            class Diaphragm {
                HitpointName = "HitDiaphragm";
                armor = 20;
                PassThrough = 0.500000;
            };

            class Abdomen {
                hitpointName = "HitAbdomen";
                armor = 20;
                passThrough = 0.500000;
            };

            class Body {
                hitpointName = "HitBody";
                passThrough = 0.500000;
            };
        };
    };
};

class ARC_Common_OD_Plate_Carrier_H : V_PlateCarrier2_rgr {
  picture = "\Common_items\data\UI\Icon_Common_OD_vests.paa";	
  displayName = "(ARC) Common Heavy Plate Carrier (OD)";
  hiddenSelections[] = {"camo"};
  hiddenSelectionsTextures[] = {"\Common_items\data\Vests\Common_OD_vests.paa"};

      class ItemInfo: VestItem {
          containerclass = "Supply120";
          mass = 80;
          uniformmodel = "\A3\Characters_F\BLUFOR\equip_b_vest01";
          hiddenSelections[] = {
            "camo"
        };
        class HitpointsProtectionInfo {

            class Chest {
                HitpointName = "HitChest";
                armor = 30;
                PassThrough = 0.500000;
            };

            class Diaphragm {
                HitpointName = "HitDiaphragm";
                armor = 30;
                PassThrough = 0.500000;
            };

            class Abdomen {
                hitpointName = "HitAbdomen";
                armor = 30;
                passThrough = 0.500000;
            };

            class Body {
                hitpointName = "HitBody";
                passThrough = 0.500000;
            };
        };
    };
};

class ARC_Common_OD_rangemaster_belt : V_Rangemaster_belt {
    displayName = "(ARC) Common Rangemaster Belt (OD)";
    model = "\A3\Characters_F\BLUFOR\equip_b_belt";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Vests\Common_OD_vests.paa"};

    class ItemInfo: VestItem {
      armor = 0;
      containerclass = "Supply40";
      mass = 20;
      passthrough = 1;
      uniformmodel = "\A3\Characters_F\BLUFOR\equip_b_belt";
      hiddenSelections[] = {
        "camo"
    };
};
};

class ARC_Common_OD_BandollierB_rgr : V_BandollierB_rgr {
  model = "\A3\Characters_F\BLUFOR\equip_b_bandolier";
  displayName = "(ARC) Common Slash Bandolier (OD)";
  hiddenSelectionsTextures[] = {"\Common_items\data\Vests\Common_OD_vests.paa"};

  class ItemInfo: ItemInfo {
    uniformClass = "ARC_USN_AOR1_Soldier_02";
    armor = 0;
    containerclass = "Supply80";
    mass = 20;
    passthrough = 1;

    uniformmodel = "\A3\Characters_F\BLUFOR\equip_b_bandolier.p3d";
    hiddenselections[] = {
        "camo"
    };
};	
};	
class ARC_Common_OD_PlateCarrier_1 : V_PlateCarrierIA1_dgtl {
    displayName = "(ARC) Common Plate Carrier 1 (OD)";
    model = "A3\Characters_F_Beta\INDEP\equip_ia_vest01";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Vests\Common_OD_PlateCarrier.paa"};

    class ItemInfo: VestItem {
      containerclass = "Supply140";
      mass = 40;
      uniformmodel = "A3\Characters_F_Beta\INDEP\equip_ia_vest01";
      hiddenSelections[] = {
        "camo"
    };
        class HitpointsProtectionInfo {

            class Chest {
                hitpointName = "HitChest";
                armor = 30;
                passThrough = 0.500000;
            };

            class Diaphragm {
                hitpointName = "HitDiaphragm";
                armor = 30;
                passThrough = 0.500000;
            };

            class Abdomen {
                hitpointName = "HitAbdomen";
                armor = 30;
                passThrough = 0.500000;
            };

            class Body {
                hitpointName = "HitBody";
                passThrough = 0.500000;
            };
        };

};
};	
class ARC_Common_OD_PlateCarrier_2 : V_PlateCarrierIA2_dgtl {
    displayName = "(ARC) Common Plate Carrier 2 (OD) ";
    model = "A3\Characters_F_Beta\INDEP\equip_ia_vest02";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Vests\Common_OD_PlateCarrier.paa"};

    class ItemInfo: VestItem {
      containerclass = "Supply140";
      mass = 60;
      uniformmodel = "A3\Characters_F_Beta\INDEP\equip_ia_vest02";
      hiddenSelections[] = {
        "camo"
    };
    class HitpointsProtectionInfo {

            class Chest {
                hitpointName = "HitChest";
                armor = 30;
                passThrough = 0.100000;
            };

            class Diaphragm {
                hitpointName = "HitDiaphragm";
                armor = 30;
                passThrough = 0.100000;
            };

            class Abdomen {
                hitpointName = "HitAbdomen";
                armor = 30;
                passThrough = 0.100000;
            };

            class Pelvis {
                hitpointName = "HitPelvis";
                armor = 30;
                passThrough = 0.100000;
            };

            class Body {
                hitpointName = "HitBody";
                passThrough = 0.100000;
            };
        };
    };
};	
// TAN
class ARC_Common_TAN_Plate_Carrier : V_PlateCarrier1_rgr {
  picture = "\Common_items\data\UI\Icon_Common_TAN_vests.paa";	
  displayName = "(ARC) Common Plate Carrier (TAN)";
  hiddenSelections[] = {"camo"};
  hiddenSelectionsTextures[] = {"\Common_items\data\Vests\Common_TAN_vests.paa"};

  class ItemInfo: VestItem {
    containerclass = "Supply140";
    mass = 60;
    uniformmodel = "\A3\Characters_F\BLUFOR\equip_b_vest02";
    hiddenSelections[] = {
        "camo"
    };
        class HitpointsProtectionInfo {

            class Chest {
                HitpointName = "HitChest";
                armor = 20;
                PassThrough = 0.500000;
            };

            class Diaphragm {
                HitpointName = "HitDiaphragm";
                armor = 20;
                PassThrough = 0.500000;
            };

            class Abdomen {
                hitpointName = "HitAbdomen";
                armor = 20;
                passThrough = 0.500000;
            };

            class Body {
                hitpointName = "HitBody";
                passThrough = 0.500000;
            };
        };
    };
};	
class ARC_Common_TAN_Plate_Carrier_H : V_PlateCarrier2_rgr {
  picture = "\Common_items\data\UI\Icon_Common_TAN_vests.paa";	
  displayName = "(ARC) Common Heavy Plate Carrier (TAN)";
  hiddenSelections[] = {"camo"};
  hiddenSelectionsTextures[] = {"\Common_items\data\Vests\Common_TAN_vests.paa"};

  class ItemInfo: VestItem {
      containerclass = "Supply120";
      mass = 80;
      uniformmodel = "\A3\Characters_F\BLUFOR\equip_b_vest01";
      hiddenSelections[] = {
        "camo"
    };
        class HitpointsProtectionInfo {

            class Chest {
                HitpointName = "HitChest";
                armor = 30;
                PassThrough = 0.500000;
            };

            class Diaphragm {
                HitpointName = "HitDiaphragm";
                armor = 30;
                PassThrough = 0.500000;
            };

            class Abdomen {
                hitpointName = "HitAbdomen";
                armor = 30;
                passThrough = 0.500000;
            };

            class Body {
                hitpointName = "HitBody";
                passThrough = 0.500000;
            };
        };
    };
};	
class ARC_Common_TAN_rangemaster_belt : V_Rangemaster_belt {
    displayName = "(ARC) Common Rangemaster Belt (TAN)";
    model = "\A3\Characters_F\BLUFOR\equip_b_belt";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Vests\Common_TAN_vests.paa"};

    class ItemInfo: VestItem {
      armor = 0;
      containerclass = "Supply40";
      mass = 20;
      passthrough = 1;
      uniformmodel = "\A3\Characters_F\BLUFOR\equip_b_belt";
      hiddenSelections[] = {
        "camo"
    };
};
};
class ARC_Common_TAN_BandollierB_rgr : V_BandollierB_rgr {
  model = "\A3\Characters_F\BLUFOR\equip_b_bandolier";
  displayName = "(ARC) Common Slash Bandolier (TAN)";
  hiddenSelectionsTextures[] = {"\Common_items\data\Vests\Common_TAN_vests.paa"};

  class ItemInfo: ItemInfo {
    uniformClass = "ARC_USN_AOR1_Soldier_02";
    armor = 0;
    containerclass = "Supply80";
    mass = 20;
    passthrough = 1;

    uniformmodel = "\A3\Characters_F\BLUFOR\equip_b_bandolier.p3d";
    hiddenselections[] = {
        "camo"
    };
};	
};	
class ARC_Common_TAN_PlateCarrier_1 : V_PlateCarrierIA1_dgtl {
    displayName = "(ARC) Common Plate Carrier 1 (TAN)";
    model = "A3\Characters_F_Beta\INDEP\equip_ia_vest01";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Vests\Common_TAN_PlateCarrier.paa"};

    class ItemInfo: VestItem {
      containerclass = "Supply140";
      mass = 40;
      uniformmodel = "A3\Characters_F_Beta\INDEP\equip_ia_vest01";
      hiddenSelections[] = {
        "camo"
      };
        class HitpointsProtectionInfo {

            class Chest {
                hitpointName = "HitChest";
                armor = 30;
                passThrough = 0.500000;
            };

            class Diaphragm {
                hitpointName = "HitDiaphragm";
                armor = 30;
                passThrough = 0.500000;
            };

            class Abdomen {
                hitpointName = "HitAbdomen";
                armor = 30;
                passThrough = 0.500000;
            };

            class Body {
                hitpointName = "HitBody";
                passThrough = 0.500000;
            };
        };
    };
};	
class ARC_Common_TAN_PlateCarrier_2 : V_PlateCarrierIA2_dgtl {
    displayName = "(ARC) Common Plate Carrier 2 (TAN) ";
    model = "A3\Characters_F_Beta\INDEP\equip_ia_vest02";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Vests\Common_TAN_PlateCarrier.paa"};

    class ItemInfo: VestItem {
      containerclass = "Supply140";
      mass = 60;
      uniformmodel = "A3\Characters_F_Beta\INDEP\equip_ia_vest02";
      hiddenSelections[] = {
        "camo"
    };
    class HitpointsProtectionInfo {

            class Chest {
                hitpointName = "HitChest";
                armor = 30;
                passThrough = 0.100000;
            };

            class Diaphragm {
                hitpointName = "HitDiaphragm";
                armor = 30;
                passThrough = 0.100000;
            };

            class Abdomen {
                hitpointName = "HitAbdomen";
                armor = 30;
                passThrough = 0.100000;
            };

            class Pelvis {
                hitpointName = "HitPelvis";
                armor = 30;
                passThrough = 0.100000;
            };

            class Body {
                hitpointName = "HitBody";
                passThrough = 0.100000;
            };
        };
    };
};	
// Cbr
class ARC_Common_Cbr_Plate_Carrier : V_PlateCarrier1_rgr {
  picture = "\Common_items\data\UI\Icon_Common_Cbr_vests.paa";	
  displayName = "(ARC) Common Plate Carrier (Cbr)";
  hiddenSelections[] = {"camo"};
  hiddenSelectionsTextures[] = {"\Common_items\data\Vests\Common_Cbr_vests.paa"};

  class ItemInfo: VestItem {
    containerclass = "Supply140";
    mass = 60;
    uniformmodel = "\A3\Characters_F\BLUFOR\equip_b_vest02";
    hiddenSelections[] = {
        "camo"
    };
        class HitpointsProtectionInfo {

            class Chest {
                HitpointName = "HitChest";
                armor = 20;
                PassThrough = 0.500000;
            };

            class Diaphragm {
                HitpointName = "HitDiaphragm";
                armor = 20;
                PassThrough = 0.500000;
            };

            class Abdomen {
                hitpointName = "HitAbdomen";
                armor = 20;
                passThrough = 0.500000;
            };

            class Body {
                hitpointName = "HitBody";
                passThrough = 0.500000;
            };
        };
    };
};	
class ARC_Common_Cbr_Plate_Carrier_H : V_PlateCarrier2_rgr {
  picture = "\Common_items\data\UI\Icon_Common_Cbr_vests.paa";	
  displayName = "(ARC) Common Heavy Plate Carrier (Cbr)";
  hiddenSelections[] = {"camo"};
  hiddenSelectionsTextures[] = {"\Common_items\data\Vests\Common_Cbr_vests.paa"};

  class ItemInfo: VestItem {
      containerclass = "Supply120";
      mass = 80;
      uniformmodel = "\A3\Characters_F\BLUFOR\equip_b_vest01";
      hiddenSelections[] = {
        "camo"
    };
        class HitpointsProtectionInfo {

            class Chest {
                HitpointName = "HitChest";
                armor = 30;
                PassThrough = 0.500000;
            };

            class Diaphragm {
                HitpointName = "HitDiaphragm";
                armor = 30;
                PassThrough = 0.500000;
            };

            class Abdomen {
                hitpointName = "HitAbdomen";
                armor = 30;
                passThrough = 0.500000;
            };

            class Body {
                hitpointName = "HitBody";
                passThrough = 0.500000;
            };
        };
    };
};	
class ARC_Common_Cbr_rangemaster_belt : V_Rangemaster_belt {
    displayName = "(ARC) Common Rangemaster Belt (Cbr)";
    model = "\A3\Characters_F\BLUFOR\equip_b_belt";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Vests\Common_Cbr_vests.paa"};

    class ItemInfo: VestItem {
      armor = 0;
      containerclass = "Supply40";
      mass = 20;
      passthrough = 1;
      uniformmodel = "\A3\Characters_F\BLUFOR\equip_b_belt";
      hiddenSelections[] = {
        "camo"
    };
};
};
class ARC_Common_Cbr_BandollierB_rgr : V_BandollierB_rgr {
  model = "\A3\Characters_F\BLUFOR\equip_b_bandolier";
  displayName = "(ARC) Common Slash Bandolier (Cbr)";
  hiddenSelectionsTextures[] = {"\Common_items\data\Vests\Common_Cbr_vests.paa"};

  class ItemInfo: ItemInfo {
    uniformClass = "ARC_USN_AOR1_Soldier_02";
    armor = 0;
    containerclass = "Supply80";
    mass = 20;
    passthrough = 1;

    uniformmodel = "\A3\Characters_F\BLUFOR\equip_b_bandolier.p3d";
    hiddenselections[] = {
        "camo"
    };
};	
};	
class ARC_Common_Cbr_PlateCarrier_1 : V_PlateCarrierIA1_dgtl {
    displayName = "(ARC) Common Plate Carrier 1 (Cbr)";
    model = "A3\Characters_F_Beta\INDEP\equip_ia_vest01";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Vests\Common_Cbr_PlateCarrier.paa"};

    class ItemInfo: VestItem {
      containerclass = "Supply140";
      mass = 40;
      uniformmodel = "A3\Characters_F_Beta\INDEP\equip_ia_vest01";
      hiddenSelections[] = {
        "camo"
    };
        class HitpointsProtectionInfo {

            class Chest {
                hitpointName = "HitChest";
                armor = 30;
                passThrough = 0.500000;
            };

            class Diaphragm {
                hitpointName = "HitDiaphragm";
                armor = 30;
                passThrough = 0.500000;
            };

            class Abdomen {
                hitpointName = "HitAbdomen";
                armor = 30;
                passThrough = 0.500000;
            };

            class Body {
                hitpointName = "HitBody";
                passThrough = 0.500000;
            };
        };
    };
};	
class ARC_Common_Cbr_PlateCarrier_2 : V_PlateCarrierIA2_dgtl {
    displayName = "(ARC) Common Plate Carrier 2 (Cbr) ";
    model = "A3\Characters_F_Beta\INDEP\equip_ia_vest02";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Vests\Common_Cbr_PlateCarrier.paa"};

    class ItemInfo: VestItem {
      containerclass = "Supply140";
      mass = 60;
      uniformmodel = "A3\Characters_F_Beta\INDEP\equip_ia_vest02";
      hiddenSelections[] = {
        "camo"
    };
        class HitpointsProtectionInfo {

            class Chest {
                hitpointName = "HitChest";
                armor = 30;
                passThrough = 0.100000;
            };

            class Diaphragm {
                hitpointName = "HitDiaphragm";
                armor = 30;
                passThrough = 0.100000;
            };

            class Abdomen {
                hitpointName = "HitAbdomen";
                armor = 30;
                passThrough = 0.100000;
            };

            class Pelvis {
                hitpointName = "HitPelvis";
                armor = 30;
                passThrough = 0.100000;
            };

            class Body {
                hitpointName = "HitBody";
                passThrough = 0.100000;
            };
        };
    };	
};	
//// Black

class ARC_Common_Blk_Plate_Carrier : V_PlateCarrier1_rgr {
  picture = "\Common_items\data\UI\Icon_Common_Blk_vests.paa";	
  displayName = "(ARC) Common Plate Carrier (Black)";
  hiddenSelections[] = {"camo"};
  hiddenSelectionsTextures[] = {"\Common_items\data\Vests\Common_Blk_vests.paa"};

  class ItemInfo: VestItem {
    containerclass = "Supply140";
    mass = 60;
    uniformmodel = "\A3\Characters_F\BLUFOR\equip_b_vest02";
    hiddenSelections[] = {
        "camo"
    };
        class HitpointsProtectionInfo {

            class Chest {
                HitpointName = "HitChest";
                armor = 20;
                PassThrough = 0.500000;
            };

            class Diaphragm {
                HitpointName = "HitDiaphragm";
                armor = 20;
                PassThrough = 0.500000;
            };

            class Abdomen {
                hitpointName = "HitAbdomen";
                armor = 20;
                passThrough = 0.500000;
            };

            class Body {
                hitpointName = "HitBody";
                passThrough = 0.500000;
            };
        };
    };
};	
class ARC_Common_Blk_Plate_Carrier_H : V_PlateCarrier2_rgr {
  picture = "\Common_items\data\UI\Icon_Common_Blk_vests.paa";	
  displayName = "(ARC) Common Heavy Plate Carrier (Black)";
  hiddenSelections[] = {"camo"};
  hiddenSelectionsTextures[] = {"\Common_items\data\Vests\Common_Blk_vests.paa"};

  class ItemInfo: VestItem {
      containerclass = "Supply120";
      mass = 80;
      uniformmodel = "\A3\Characters_F\BLUFOR\equip_b_vest01";
      hiddenSelections[] = {
        "camo"
    };
        class HitpointsProtectionInfo {

            class Chest {
                HitpointName = "HitChest";
                armor = 30;
                PassThrough = 0.500000;
            };

            class Diaphragm {
                HitpointName = "HitDiaphragm";
                armor = 30;
                PassThrough = 0.500000;
            };

            class Abdomen {
                hitpointName = "HitAbdomen";
                armor = 30;
                passThrough = 0.500000;
            };

            class Body {
                hitpointName = "HitBody";
                passThrough = 0.500000;
            };
        };
    };
};	
class ARC_Common_Blk_rangemaster_belt : V_Rangemaster_belt {
    displayName = "(ARC) Common Rangemaster Belt (Black)";
    model = "\A3\Characters_F\BLUFOR\equip_b_belt";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Vests\Common_Blk_vests.paa"};

    class ItemInfo: VestItem {
      armor = 0;
      containerclass = "Supply40";
      mass = 20;
      passthrough = 1;
      uniformmodel = "\A3\Characters_F\BLUFOR\equip_b_belt";
      hiddenSelections[] = {
        "camo"
    };
};
};
class ARC_Common_Blk_BandollierB_rgr : V_BandollierB_rgr {
  model = "\A3\Characters_F\BLUFOR\equip_b_bandolier";
  displayName = "(ARC) Common Slash Bandolier (Black)";
  hiddenSelectionsTextures[] = {"\Common_items\data\Vests\Common_Blk_vests.paa"};

  class ItemInfo: ItemInfo {
    uniformClass = "ARC_USN_AOR1_Soldier_02";
    armor = 0;
    containerclass = "Supply80";
    mass = 20;
    passthrough = 1;

    uniformmodel = "\A3\Characters_F\BLUFOR\equip_b_bandolier.p3d";
    hiddenselections[] = {
        "camo"
    };
};	
};	
class ARC_Common_Blk_PlateCarrier_1 : V_PlateCarrierIA1_dgtl {
    displayName = "(ARC) Common Plate Carrier 1 (Black)";
    model = "A3\Characters_F_Beta\INDEP\equip_ia_vest01";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Vests\Common_Blk_PlateCarrier.paa"};

    class ItemInfo: VestItem {
      containerclass = "Supply140";
      mass = 40;
      uniformmodel = "A3\Characters_F_Beta\INDEP\equip_ia_vest01";
      hiddenSelections[] = {
        "camo"
    };
    class HitpointsProtectionInfo {

        class Chest {
            hitpointName = "HitChest";
            armor = 30;
            passThrough = 0.500000;
        };

        class Diaphragm {
            hitpointName = "HitDiaphragm";
            armor = 30;
            passThrough = 0.500000;
        };

        class Abdomen {
            hitpointName = "HitAbdomen";
            armor = 30;
            passThrough = 0.500000;
        };

        class Body {
            hitpointName = "HitBody";
            passThrough = 0.500000;
        };
    };
};
};	
class ARC_Common_Blk_PlateCarrier_2 : V_PlateCarrierIA2_dgtl {
    displayName = "(ARC) Common Plate Carrier 2 (Black) ";
    model = "A3\Characters_F_Beta\INDEP\equip_ia_vest02";
    hiddenSelections[] = {"camo"};
    hiddenSelectionsTextures[] = {"\Common_items\data\Vests\Common_Blk_PlateCarrier.paa"};

    class ItemInfo: VestItem {
      containerclass = "Supply140";
      mass = 60;
      uniformmodel = "A3\Characters_F_Beta\INDEP\equip_ia_vest02";
      hiddenSelections[] = {
        "camo"
    };
        class HitpointsProtectionInfo {

            class Chest {
                hitpointName = "HitChest";
                armor = 30;
                passThrough = 0.100000;
            };

            class Diaphragm {
                hitpointName = "HitDiaphragm";
                armor = 30;
                passThrough = 0.100000;
            };

            class Abdomen {
                hitpointName = "HitAbdomen";
                armor = 30;
                passThrough = 0.100000;
            };

            class Pelvis {
                hitpointName = "HitPelvis";
                armor = 30;
                passThrough = 0.100000;
            };

            class Body {
                hitpointName = "HitBody";
                passThrough = 0.100000;
            };
        };
    };
};	
	//////////////// Heli helmets

class ARC_PilotHelmetHeli_Evil : H_PilotHelmetHeli_B {
    displayName = "(ARC) Common Heli Helmet Evil";
    picture = "\A3\Characters_F\data\ui\icon_H_Pilot_Helmet_Heli_OI_CA.paa";
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\helmet_heli_Evil.paa"};
    model = "A3\Characters_F\Common\headgear_helmet_heli_shield";		

    class ItemInfo : ItemInfo {
     uniformModel = "A3\Characters_F\Common\headgear_helmet_heli_shield";
     modelSides[] = {0, 3};

    class HitpointsProtectionInfo {

        class Head {
            hitpointName = "HitHead";
            armor = 6;
            passThrough = 0.500000;
        };
    };
};
};

class ARC_PilotHelmetHeli_LZH : H_PilotHelmetHeli_B {
    displayName = "(ARC) Common Heli Helmet LZH";
    picture = "\A3\Characters_F\data\ui\icon_H_Pilot_Helmet_Heli_OI_CA.paa";
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\helmet_heli_LZH.paa"};

    class ItemInfo : ItemInfo {
     uniformModel = "A3\Characters_F\Common\headgear_helmet_heli";
     modelSides[] = {0, 3};

     class HitpointsProtectionInfo {

        class Head {
            hitpointName = "HitHead";
            armor = 6;
            passThrough = 0.500000;
        };
    };
 };
};	

class ARC_PilotHelmetHeli_TM : H_PilotHelmetHeli_B {
    displayName = "(ARC) Common Heli Helmet TacMen";
    picture = "\A3\Characters_F\data\ui\icon_H_Pilot_Helmet_Heli_OI_CA.paa";
    hiddenSelectionsTextures[] = {"\Common_items\data\Helmet\helmet_heli_TM.paa"};

    class ItemInfo : ItemInfo {
     uniformModel = "A3\Characters_F\Common\headgear_helmet_heli";
     modelSides[] = {0, 3};

     class HitpointsProtectionInfo {

        class Head {
            hitpointName = "HitHead";
            armor = 6;
            passThrough = 0.500000;
        };
    };
 };
};		
//// Berets

	class H_Beret_02;	// External class reference

	class ARC_Beret_UN : H_Beret_02 {
        displayName = "(ARC) Common (ARC) UN Beret";
        hiddenSelectionsTextures[] = {"Common_items\data\Beret\ARC_beret_UN.paa"};		
    };	


//// Capb


    class ARC_CapHeadPhone_TAN : H_Cap_headphones {
      author = "=ARC=";
      displayName = "(ARC) Common Cap Sordin (TAN)";
      hiddenSelectionsTextures[] = {"Common_items\data\Capb\capb_headphones_TAN.paa"};

      class ItemInfo : ItemInfo {
         hiddenSelections[] = {"camo"};
     };
 };	
 class ARC_CapHeadPhone_OD : H_Cap_headphones {
  author = "=ARC=";
  displayName = "(ARC) Common Cap Sordin (OD)";
  hiddenSelectionsTextures[] = {"Common_items\data\Capb\capb_headphones_OD.paa"};

  class ItemInfo : ItemInfo {
     hiddenSelections[] = {"camo"};
 };
};
class ARC_CapHeadPhone_Blk : H_Cap_headphones {
  author = "=ARC=";
  displayName = "(ARC) Common Cap Sordin (Black)";
  hiddenSelectionsTextures[] = {"Common_items\data\Capb\capb_headphones_Blk.paa"};

  class ItemInfo : ItemInfo {
     hiddenSelections[] = {"camo"};
 };
};		

	////// HPC
	class V_PlateCarrierGL_rgr;	// External class reference
	class V_PlateCarrierSpec_rgr;	// External class reference
	//
	
	class ARC_Common_ATACS_LE_HPC_GL : V_PlateCarrierGL_rgr {
		author = "Soronelite";
		displayName = "(ARC) Common HPC GL (ATACS LE)";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"Common_items\data\Vests\Common_ATACS_LE_HPC.paa"};
		
		class ItemInfo : ItemInfo {
			containerClass = "Supply160";
			hiddenSelections[] = {"camo"};
			mass = 90;
			uniformModel = "\A3\Characters_F\BLUFOR\equip_b_carrier_gl_rig.p3d";

            class HitpointsProtectionInfo {

                class Neck {
                    hitpointName = "HitNeck";
                    armor = 8;
                    passThrough = 0.500000;
                };

                class Arms {
                    hitpointName = "HitArms";
                    armor = 8;
                    passThrough = 0.500000;
                };

                class Chest {
                    hitpointName = "HitChest";
                    armor = 78;
                    passThrough = 0.600000;
                };

                class Diaphragm {
                    hitpointName = "HitDiaphragm";
                    armor = 78;
                    passThrough = 0.600000;
                };

                class Abdomen {
                    hitpointName = "HitAbdomen";
                    armor = 16;
                    passThrough = 0.300000;
                };

                class Pelvis {
                    hitpointName = "HitPelvis";
                    armor = 16;
                    passThrough = 0.300000;
                };

                class Body {
                    hitpointName = "HitBody";
                    passThrough = 0.600000;
                };
            };
		};
	};
	class ARC_Common_ATACS_LE_HPC : V_PlateCarrierSpec_rgr {
		author = "Soronelite";
		displayName = "(ARC) Common HPC (ATACS LE)";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"Common_items\data\Vests\Common_ATACS_LE_HPC.paa"};
		
		class ItemInfo : ItemInfo {
			containerClass = "Supply140";
			hiddenSelections[] = {"camo"};
			mass = 60;
			uniformModel = "\A3\Characters_F\BLUFOR\equip_b_carrier_spec_rig.p3d";

            class HitpointsProtectionInfo {

                class Neck {
                    hitpointName = "HitNeck";
                    armor = 8;
                    passThrough = 0.500000;
                };

                class Arms {
                    hitpointName = "HitArms";
                    armor = 8;
                    passThrough = 0.500000;
                };

                class Chest {
                    hitpointName = "HitChest";
                    armor = 78;
                    passThrough = 0.600000;
                };

                class Diaphragm {
                    hitpointName = "HitDiaphragm";
                    armor = 78;
                    passThrough = 0.600000;
                };

                class Abdomen {
                    hitpointName = "HitAbdomen";
                    armor = 16;
                    passThrough = 0.300000;
                };

                class Pelvis {
                    hitpointName = "HitPelvis";
                    armor = 16;
                    passThrough = 0.300000;
                };

                class Body {
                    hitpointName = "HitBody";
                    passThrough = 0.600000;
                };
            };
		};
	};	
	
	//
	
	class ARC_Common_Black_HPC_GL : V_PlateCarrierGL_rgr {
		author = "Soronelite";
		displayName = "(ARC) Common HPC GL (Black)";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"Common_items\data\Vests\Common_Black_HPC.paa"};
		
		class ItemInfo : ItemInfo {
			containerClass = "Supply160";
			hiddenSelections[] = {"camo"};
			mass = 90;
			uniformModel = "\A3\Characters_F\BLUFOR\equip_b_carrier_gl_rig.p3d";

            class HitpointsProtectionInfo {

                class Neck {
                    hitpointName = "HitNeck";
                    armor = 8;
                    passThrough = 0.500000;
                };

                class Arms {
                    hitpointName = "HitArms";
                    armor = 8;
                    passThrough = 0.500000;
                };

                class Chest {
                    hitpointName = "HitChest";
                    armor = 78;
                    passThrough = 0.600000;
                };

                class Diaphragm {
                    hitpointName = "HitDiaphragm";
                    armor = 78;
                    passThrough = 0.600000;
                };

                class Abdomen {
                    hitpointName = "HitAbdomen";
                    armor = 16;
                    passThrough = 0.300000;
                };

                class Pelvis {
                    hitpointName = "HitPelvis";
                    armor = 16;
                    passThrough = 0.300000;
                };

                class Body {
                    hitpointName = "HitBody";
                    passThrough = 0.600000;
                };
            };
		};
	};
	class ARC_Common_Black_HPC : V_PlateCarrierSpec_rgr {
		author = "Soronelite";
		displayName = "(ARC) Common HPC (Black)";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"Common_items\data\Vests\Common_Black_HPC.paa"};
		
		class ItemInfo : ItemInfo {
			containerClass = "Supply140";
			hiddenSelections[] = {"camo"};
			mass = 60;
			uniformModel = "\A3\Characters_F\BLUFOR\equip_b_carrier_spec_rig.p3d";

            class HitpointsProtectionInfo {

                class Neck {
                    hitpointName = "HitNeck";
                    armor = 8;
                    passThrough = 0.500000;
                };

                class Arms {
                    hitpointName = "HitArms";
                    armor = 8;
                    passThrough = 0.500000;
                };

                class Chest {
                    hitpointName = "HitChest";
                    armor = 24;
                    passThrough = 0.100000;
                };

                class Diaphragm {
                    hitpointName = "HitDiaphragm";
                    armor = 24;
                    passThrough = 0.100000;
                };

                class Abdomen {
                    hitpointName = "HitAbdomen";
                    armor = 24;
                    passThrough = 0.100000;
                };

                class Body {
                    hitpointName = "HitBody";
                    passThrough = 0.100000;
                };
            };
		};
	};	
	
	//
	
	class ARC_Common_OD_HPC_GL : V_PlateCarrierGL_rgr {
		author = "Soronelite";
		displayName = "(ARC) Common HPC GL (OD)";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"Common_items\data\Vests\Common_OD_HPC.paa"};
		
		class ItemInfo : ItemInfo {
			containerClass = "Supply160";
			hiddenSelections[] = {"camo"};
			mass = 90;
			uniformModel = "\A3\Characters_F\BLUFOR\equip_b_carrier_gl_rig.p3d";

            class HitpointsProtectionInfo {

                class Neck {
                    hitpointName = "HitNeck";
                    armor = 8;
                    passThrough = 0.500000;
                };

                class Arms {
                    hitpointName = "HitArms";
                    armor = 8;
                    passThrough = 0.500000;
                };

                class Chest {
                    hitpointName = "HitChest";
                    armor = 78;
                    passThrough = 0.600000;
                };

                class Diaphragm {
                    hitpointName = "HitDiaphragm";
                    armor = 78;
                    passThrough = 0.600000;
                };

                class Abdomen {
                    hitpointName = "HitAbdomen";
                    armor = 16;
                    passThrough = 0.300000;
                };

                class Pelvis {
                    hitpointName = "HitPelvis";
                    armor = 16;
                    passThrough = 0.300000;
                };

                class Body {
                    hitpointName = "HitBody";
                    passThrough = 0.600000;
                };
            };
		};
	};
	class ARC_Common_OD_HPC : V_PlateCarrierSpec_rgr {
		author = "Soronelite";
		displayName = "(ARC) Common HPC (OD)";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"Common_items\data\Vests\Common_OD_HPC.paa"};
		
		class ItemInfo : ItemInfo {
			containerClass = "Supply140";
			hiddenSelections[] = {"camo"};
			mass = 60;
			uniformModel = "\A3\Characters_F\BLUFOR\equip_b_carrier_spec_rig.p3d";

            class HitpointsProtectionInfo {

                class Neck {
                    hitpointName = "HitNeck";
                    armor = 8;
                    passThrough = 0.500000;
                };

                class Arms {
                    hitpointName = "HitArms";
                    armor = 8;
                    passThrough = 0.500000;
                };

                class Chest {
                    hitpointName = "HitChest";
                    armor = 24;
                    passThrough = 0.100000;
                };

                class Diaphragm {
                    hitpointName = "HitDiaphragm";
                    armor = 24;
                    passThrough = 0.100000;
                };

                class Abdomen {
                    hitpointName = "HitAbdomen";
                    armor = 24;
                    passThrough = 0.100000;
                };

                class Body {
                    hitpointName = "HitBody";
                    passThrough = 0.100000;
                };
            };
		};
	};	
	//
	
	class ARC_Common_TAN_HPC_GL : V_PlateCarrierGL_rgr {
		author = "Soronelite";
		displayName = "(ARC) Common HPC GL (TAN)";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"Common_items\data\Vests\Common_TAN_HPC.paa"};
		
		class ItemInfo : ItemInfo {
			containerClass = "Supply160";
			hiddenSelections[] = {"camo"};
			mass = 90;
			uniformModel = "\A3\Characters_F\BLUFOR\equip_b_carrier_gl_rig.p3d";

            class HitpointsProtectionInfo {

                class Neck {
                    hitpointName = "HitNeck";
                    armor = 8;
                    passThrough = 0.500000;
                };

                class Arms {
                    hitpointName = "HitArms";
                    armor = 8;
                    passThrough = 0.500000;
                };

                class Chest {
                    hitpointName = "HitChest";
                    armor = 78;
                    passThrough = 0.600000;
                };

                class Diaphragm {
                    hitpointName = "HitDiaphragm";
                    armor = 78;
                    passThrough = 0.600000;
                };

                class Abdomen {
                    hitpointName = "HitAbdomen";
                    armor = 16;
                    passThrough = 0.300000;
                };

                class Pelvis {
                    hitpointName = "HitPelvis";
                    armor = 16;
                    passThrough = 0.300000;
                };

                class Body {
                    hitpointName = "HitBody";
                    passThrough = 0.600000;
                };
            };
		};
	};
	class ARC_Common_TAN_HPC : V_PlateCarrierSpec_rgr {
		author = "Soronelite";
		displayName = "(ARC) Common HPC (TAN)";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"Common_items\data\Vests\Common_TAN_HPC.paa"};
		
		class ItemInfo : ItemInfo {
			containerClass = "Supply140";
			hiddenSelections[] = {"camo"};
			mass = 60;
			uniformModel = "\A3\Characters_F\BLUFOR\equip_b_carrier_spec_rig.p3d";

            class HitpointsProtectionInfo {

                class Neck {
                    hitpointName = "HitNeck";
                    armor = 8;
                    passThrough = 0.500000;
                };

                class Arms {
                    hitpointName = "HitArms";
                    armor = 8;
                    passThrough = 0.500000;
                };

                class Chest {
                    hitpointName = "HitChest";
                    armor = 24;
                    passThrough = 0.100000;
                };

                class Diaphragm {
                    hitpointName = "HitDiaphragm";
                    armor = 24;
                    passThrough = 0.100000;
                };

                class Abdomen {
                    hitpointName = "HitAbdomen";
                    armor = 24;
                    passThrough = 0.100000;
                };

                class Body {
                    hitpointName = "HitBody";
                    passThrough = 0.100000;
                };
            };
		};
	};		
	
};	
